spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
    schema: classpath:setup-tables.sql

  h2:
    console:
      enabled: on
      path: /h2
